name: Setup sotracteur databases

on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Database to setup'
        type: 'choice'
        options:
          - 'postgres-bleu'
          - 'postgres-marron'
          - 'postgres-or'
          - 'postgres-orange'
          - 'postgres-rouge'
          - 'postgres-rose'
          - 'postgres-vert'
          - 'postgres-violet'
          - 'mongo-bleu'
          - 'mongo-marron'
          - 'mongo-or'
          - 'mongo-orange'
          - 'mongo-rouge'
          - 'mongo-rose'
          - 'mongo-vert'
          - 'mongo-violet'

jobs:
  setup-postgres-rose:
    if: github.event.inputs.database == 'postgres-rose'
    uses: ./.github/workflows/start-postgres.yml
    with:
      color: 'rose'
      host: rose.aus.floless.fr
    secrets:
      ssh_key: ${{ secrets.SSH_KEY }}
      ssh_user: ${{ secrets.SSH_USER }}
